name: Deploy Website Using Surge

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Job_Deploy_Surge
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJs
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: Setup_Surge
      run: npm install --global surge
    - name: Execute Deployment with Surge
      run: surge ./ Bootcamp2020_Bilal.surge.sh --token ${{secrets.SURGE_TOKEN_BOOTCAMP}}
